# Generated by Django 5.1 on 2024-09-02 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("level_lounge", "0003_post_exercpt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
