# Generated by Django 5.1 on 2024-09-02 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("level_lounge", "0005_alter_post_author_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-created_at"]},
        ),
    ]
