# Generated by Django 5.1 on 2024-09-02 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("level_lounge", "0006_alter_comment_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="author",
            new_name="user",
        ),
    ]
