# Generated by Django 5.1 on 2024-09-05 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("level_lounge", "0007_rename_author_comment_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="exercpt",
            new_name="excerpt",
        ),
    ]
