# Generated by Django 5.1 on 2024-09-12 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("level_lounge", "0009_rename_parent_comment_comment_parent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="updated_at",
        ),
    ]
