# Generated by Django 5.1 on 2024-09-16 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("level_lounge", "0010_remove_comment_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="post_number",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
