# Generated by Django 5.1 on 2024-09-19 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("level_lounge", "0011_userprofile_post_number"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="created_at",
            new_name="joined_on",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="post_number",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="post_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
