# Generated by Django 5.1 on 2024-09-19 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("level_lounge", "0014_alter_userprofile_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="profile_pics/default-avatar-icon.jpg",
                null=True,
                upload_to="profile_pics/",
            ),
        ),
    ]
