# Generated by Django 5.1 on 2024-09-25 10:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("level_lounge", "0021_alter_userprofile_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="profile_picture",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                default="https://res.cloudinary.com/dxckubce0/image/upload/v1/default-avatar-icon_igvupd.webp",
                max_length=255,
                null=True,
                verbose_name="image",
            ),
        ),
    ]
