# Generated by Django 5.1 on 2024-09-26 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("level_lounge", "0024_alter_userprofile_profile_picture"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="updated_at",
        ),
    ]
