# Generated by Django 5.1 on 2024-09-26 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("level_lounge", "0025_remove_post_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
